<?php

// @audit-skip: line-limit

declare(strict_types=1);

namespace App\Providers;

use App\Adapters\Out\Note\DatabaseDueNoteReminderReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteCorrectionHistoryReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteHistoryProjectionSourceReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteHistoryProjectionWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteMutationEventWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteMutationSnapshotWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteRevisionSettlementAdapter;
use App\Adapters\Out\Note\DatabaseNoteRevisionSurplusDispositionAdapter;
use App\Adapters\Out\Note\DatabaseNoteRevisionSurplusRefundDueSourceReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteRevisionSurplusRefundPaymentAdapter;
use App\Adapters\Out\Note\DatabaseNoteSurplusDispositionAuditTimelineReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteWriterAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftDeleterAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftReaderAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftWriterAdapter;
use App\Adapters\Out\Note\DatabaseWorkItemWriterAdapter;
use App\Adapters\Out\Note\DatabaseWorkItemStoreStockLineReaderAdapter;
use App\Adapters\Out\Note\Queries\AdminNoteHistoryTableQuery;
use App\Adapters\Out\Note\Queries\CashierNoteHistoryTableQuery;
use App\Adapters\Out\Payment\DatabaseCustomerPaymentReaderAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerPaymentWriterAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerRefundReaderAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerRefundWriterAdapter;
use App\Adapters\Out\Payment\DatabaseRefundComponentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabaseRefundComponentAllocationWriterAdapter;
use App\Adapters\Out\Payment\DatabasePaymentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabasePaymentAllocationWriterAdapter;
use App\Adapters\Out\Payment\DatabasePaymentComponentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabasePaymentComponentAllocationWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceLineReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceListProjectionSourceReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceListProjectionWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierListProjectionSourceReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierListProjectionWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceDuplicateNumberCheckerAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceVoidStatusReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceVoidWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseVersionedSupplierInvoiceWriterAdapter;
use App\Application\Procurement\Context\SupplierInvoiceChangeContext;
use App\Adapters\Out\Procurement\DatabaseProcurementInvoiceDetailReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentProofAttachmentReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentProofAttachmentWriterAdapter;
use App\Adapters\Out\Procurement\LaravelSupplierPaymentProofFileStorageAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentReversalWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPayableReminderReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReceiptLineReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReceiptReversalWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReceiptWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseProcurementInvoiceTableReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierTableReaderAdapter;
use App\Application\Note\Policies\NoteAddabilityPolicy;
use App\Application\Note\Policies\CashierNoteAccessGuard;
use App\Application\Note\Policies\NotePaidStatusPolicy;
use App\Application\Note\Services\AddWorkItemErrorClassifier;
use App\Application\Note\Services\BuildNoteRevisionSettlement;
use App\Application\Note\Services\BuildCreateNoteRevisionSettlement;
use App\Application\Note\Services\AutoCloseNoteWhenFullyPaid;
use App\Application\Note\Services\NoteCorrectionSnapshotBuilder;
use App\Application\Note\Services\NoteHistoryProjectionService;
use App\Application\Note\Services\NoteRowSettlementSummaryBuilder;
use App\Application\Note\Services\PersistNoteMutationTimeline;
use App\Application\Note\Services\FinalizePaidNoteCorrection;
use App\Application\Note\Services\WorkItemFactory;
use App\Application\Note\Services\WorkItemStatusTransitionService;
use App\Application\Payment\Services\AllocatePaymentAcrossComponents;
use App\Application\Payment\Services\AllocatePaymentErrorClassifier;
use App\Application\Payment\Services\AllocateRefundAcrossComponents;
use App\Application\Payment\Services\ResolveNotePayableComponents;
use App\Application\Procurement\Services\SupplierInvoiceFactory;
use App\Application\Procurement\Services\SupplierInvoiceListProjectionService;
use App\Application\Procurement\Services\SupplierListProjectionService;
use App\Application\Procurement\Services\SupplierReceiptFactory;
use App\Application\Procurement\Services\SupplierService;
use App\Ports\Out\Note\AdminNoteHistoryTableReaderPort;
use App\Ports\Out\Note\CashierNoteHistoryTableReaderPort;
use App\Ports\Out\Note\DueNoteReminderReaderPort;
use App\Ports\Out\Note\NoteCorrectionHistoryReaderPort;
use App\Ports\Out\Note\NoteHistoryProjectionSourceReaderPort;
use App\Ports\Out\Note\NoteHistoryProjectionWriterPort;
use App\Ports\Out\Note\NoteMutationEventWriterPort;
use App\Ports\Out\Note\NoteMutationSnapshotWriterPort;
use App\Ports\Out\Note\NoteRevisionSettlementReaderPort;
use App\Ports\Out\Note\NoteRevisionSettlementWriterPort;
use App\Ports\Out\Note\NoteRevisionSurplusDispositionReaderPort;
use App\Ports\Out\Note\NoteRevisionSurplusDispositionWriterPort;
use App\Ports\Out\Note\NoteRevisionSurplusRefundDueSourceReaderPort;
use App\Ports\Out\Note\NoteRevisionSurplusRefundPaymentReaderPort;
use App\Ports\Out\Note\NoteRevisionSurplusRefundPaymentWriterPort;
use App\Ports\Out\Note\NoteSurplusDispositionAuditTimelineReaderPort;
use App\Ports\Out\Note\NoteReaderPort;
use App\Ports\Out\Note\NoteWriterPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftDeleterPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftReaderPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftWriterPort;
use App\Ports\Out\Note\WorkItemWriterPort;
use App\Ports\Out\Note\WorkItemStoreStockLineReaderPort;
use App\Ports\Out\Payment\CustomerPaymentReaderPort;
use App\Ports\Out\Payment\CustomerPaymentWriterPort;
use App\Ports\Out\Payment\CustomerRefundReaderPort;
use App\Ports\Out\Payment\CustomerRefundWriterPort;
use App\Ports\Out\Payment\PaymentAllocationReaderPort;
use App\Ports\Out\Payment\PaymentAllocationWriterPort;
use App\Ports\Out\Payment\PaymentComponentAllocationReaderPort;
use App\Ports\Out\Payment\PaymentComponentAllocationWriterPort;
use App\Ports\Out\Payment\RefundComponentAllocationReaderPort;
use App\Ports\Out\Payment\RefundComponentAllocationWriterPort;
use App\Ports\Out\Procurement\SupplierInvoiceLifecyclePort;
use App\Ports\Out\Procurement\SupplierInvoiceListProjectionSourceReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceListProjectionWriterPort;
use App\Ports\Out\Procurement\SupplierListProjectionSourceReaderPort;
use App\Ports\Out\Procurement\SupplierListProjectionWriterPort;
use App\Ports\Out\Procurement\SupplierInvoiceLineReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceDuplicateNumberCheckerPort;
use App\Ports\Out\Procurement\SupplierInvoiceVoidStatusReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceVoidWriterPort;
use App\Ports\Out\Procurement\SupplierInvoiceWriterPort;
use App\Ports\Out\Procurement\ProcurementInvoiceDetailReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentProofAttachmentReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentProofAttachmentWriterPort;
use App\Ports\Out\Procurement\SupplierPaymentProofFileStoragePort;
use App\Ports\Out\Procurement\SupplierPaymentReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentReversalWriterPort;
use App\Ports\Out\Procurement\SupplierPayableReminderReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentWriterPort;
use App\Ports\Out\Procurement\SupplierReaderPort;
use App\Ports\Out\Procurement\SupplierReceiptLineReaderPort;
use App\Ports\Out\Procurement\SupplierReceiptReversalWriterPort;
use App\Ports\Out\Procurement\SupplierReceiptWriterPort;
use App\Ports\Out\Procurement\SupplierWriterPort;
use App\Ports\Out\Procurement\ProcurementInvoiceTableReaderPort;
use App\Ports\Out\Procurement\SupplierTableReaderPort;
use Illuminate\Support\ServiceProvider;

class HexagonalServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->singleton(NotePaidStatusPolicy::class);
        $this->app->singleton(NoteAddabilityPolicy::class);
        $this->app->singleton(CashierNoteAccessGuard::class);

        $this->app->singleton(WorkItemFactory::class);
        $this->app->singleton(WorkItemStatusTransitionService::class);
        $this->app->singleton(AddWorkItemErrorClassifier::class);
        $this->app->singleton(AutoCloseNoteWhenFullyPaid::class);
        $this->app->singleton(NoteCorrectionSnapshotBuilder::class);
        $this->app->singleton(NoteHistoryProjectionService::class);
        $this->app->singleton(NoteRowSettlementSummaryBuilder::class);
        $this->app->singleton(BuildNoteRevisionSettlement::class);
        $this->app->singleton(BuildCreateNoteRevisionSettlement::class);
        $this->app->singleton(PersistNoteMutationTimeline::class);
        $this->app->singleton(FinalizePaidNoteCorrection::class);
        $this->app->singleton(AllocatePaymentErrorClassifier::class);
        $this->app->singleton(ResolveNotePayableComponents::class);
        $this->app->singleton(AllocatePaymentAcrossComponents::class);
        $this->app->singleton(AllocateRefundAcrossComponents::class);
        $this->app->singleton(SupplierService::class);
        $this->app->singleton(SupplierInvoiceFactory::class);
        $this->app->singleton(SupplierInvoiceListProjectionService::class);
        $this->app->singleton(SupplierListProjectionService::class);
        $this->app->singleton(SupplierReceiptFactory::class);
        $this->app->scoped(SupplierInvoiceChangeContext::class, fn (): SupplierInvoiceChangeContext => new SupplierInvoiceChangeContext());

        $this->app->singleton(SupplierReaderPort::class, DatabaseSupplierReaderAdapter::class);
        $this->app->singleton(SupplierWriterPort::class, DatabaseSupplierWriterAdapter::class);
        $this->app->singleton(ProcurementInvoiceTableReaderPort::class, DatabaseProcurementInvoiceTableReaderAdapter::class);
        $this->app->singleton(SupplierTableReaderPort::class, DatabaseSupplierTableReaderAdapter::class);
        $this->app->scoped(SupplierInvoiceWriterPort::class, DatabaseVersionedSupplierInvoiceWriterAdapter::class);
        $this->app->scoped(SupplierInvoiceLifecyclePort::class, DatabaseVersionedSupplierInvoiceWriterAdapter::class);
        $this->app->singleton(SupplierInvoiceReaderPort::class, DatabaseSupplierInvoiceReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceDuplicateNumberCheckerPort::class, DatabaseSupplierInvoiceDuplicateNumberCheckerAdapter::class);
        $this->app->singleton(SupplierInvoiceVoidStatusReaderPort::class, DatabaseSupplierInvoiceVoidStatusReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceVoidWriterPort::class, DatabaseSupplierInvoiceVoidWriterAdapter::class);
        $this->app->singleton(ProcurementInvoiceDetailReaderPort::class, DatabaseProcurementInvoiceDetailReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceLineReaderPort::class, DatabaseSupplierInvoiceLineReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceListProjectionSourceReaderPort::class, DatabaseSupplierInvoiceListProjectionSourceReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceListProjectionWriterPort::class, DatabaseSupplierInvoiceListProjectionWriterAdapter::class);
        $this->app->singleton(SupplierListProjectionSourceReaderPort::class, DatabaseSupplierListProjectionSourceReaderAdapter::class);
        $this->app->singleton(SupplierListProjectionWriterPort::class, DatabaseSupplierListProjectionWriterAdapter::class);
        $this->app->singleton(SupplierReceiptLineReaderPort::class, DatabaseSupplierReceiptLineReaderAdapter::class);
        $this->app->singleton(SupplierReceiptReversalWriterPort::class, DatabaseSupplierReceiptReversalWriterAdapter::class);
        $this->app->singleton(SupplierReceiptWriterPort::class, DatabaseSupplierReceiptWriterAdapter::class);
        $this->app->singleton(SupplierPaymentWriterPort::class, DatabaseSupplierPaymentWriterAdapter::class);
        $this->app->singleton(SupplierPaymentReaderPort::class, DatabaseSupplierPaymentReaderAdapter::class);
        $this->app->singleton(SupplierPaymentReversalWriterPort::class, DatabaseSupplierPaymentReversalWriterAdapter::class);
        $this->app->singleton(SupplierPayableReminderReaderPort::class, DatabaseSupplierPayableReminderReaderAdapter::class);
        $this->app->singleton(SupplierPaymentProofAttachmentWriterPort::class, DatabaseSupplierPaymentProofAttachmentWriterAdapter::class);
        $this->app->singleton(SupplierPaymentProofAttachmentReaderPort::class, DatabaseSupplierPaymentProofAttachmentReaderAdapter::class);
        $this->app->singleton(SupplierPaymentProofFileStoragePort::class, LaravelSupplierPaymentProofFileStorageAdapter::class);

        $this->app->singleton(NoteReaderPort::class, DatabaseNoteReaderAdapter::class);
        $this->app->singleton(NoteWriterPort::class, DatabaseNoteWriterAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftWriterPort::class, DatabaseTransactionWorkspaceDraftWriterAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftReaderPort::class, DatabaseTransactionWorkspaceDraftReaderAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftDeleterPort::class, DatabaseTransactionWorkspaceDraftDeleterAdapter::class);
        $this->app->singleton(WorkItemWriterPort::class, DatabaseWorkItemWriterAdapter::class);
        $this->app->singleton(WorkItemStoreStockLineReaderPort::class, DatabaseWorkItemStoreStockLineReaderAdapter::class);
        $this->app->singleton(NoteMutationEventWriterPort::class, DatabaseNoteMutationEventWriterAdapter::class);
        $this->app->singleton(NoteMutationSnapshotWriterPort::class, DatabaseNoteMutationSnapshotWriterAdapter::class);
        $this->app->singleton(DueNoteReminderReaderPort::class, DatabaseDueNoteReminderReaderAdapter::class);
        $this->app->singleton(NoteCorrectionHistoryReaderPort::class, DatabaseNoteCorrectionHistoryReaderAdapter::class);
        $this->app->singleton(NoteHistoryProjectionSourceReaderPort::class, DatabaseNoteHistoryProjectionSourceReaderAdapter::class);
        $this->app->singleton(NoteHistoryProjectionWriterPort::class, DatabaseNoteHistoryProjectionWriterAdapter::class);
        $this->app->singleton(NoteRevisionSettlementWriterPort::class, DatabaseNoteRevisionSettlementAdapter::class);
        $this->app->singleton(NoteRevisionSettlementReaderPort::class, DatabaseNoteRevisionSettlementAdapter::class);
        $this->app->singleton(NoteRevisionSurplusDispositionReaderPort::class, DatabaseNoteRevisionSurplusDispositionAdapter::class);
        $this->app->singleton(NoteRevisionSurplusDispositionWriterPort::class, DatabaseNoteRevisionSurplusDispositionAdapter::class);
        $this->app->singleton(NoteRevisionSurplusRefundDueSourceReaderPort::class, DatabaseNoteRevisionSurplusRefundDueSourceReaderAdapter::class);
        $this->app->singleton(NoteRevisionSurplusRefundPaymentReaderPort::class, DatabaseNoteRevisionSurplusRefundPaymentAdapter::class);
        $this->app->singleton(NoteRevisionSurplusRefundPaymentWriterPort::class, DatabaseNoteRevisionSurplusRefundPaymentAdapter::class);
        $this->app->singleton(NoteSurplusDispositionAuditTimelineReaderPort::class, DatabaseNoteSurplusDispositionAuditTimelineReaderAdapter::class);
        $this->app->singleton(CashierNoteHistoryTableReaderPort::class, CashierNoteHistoryTableQuery::class);
        $this->app->singleton(AdminNoteHistoryTableReaderPort::class, AdminNoteHistoryTableQuery::class);

        $this->app->singleton(CustomerPaymentWriterPort::class, DatabaseCustomerPaymentWriterAdapter::class);
        $this->app->singleton(CustomerPaymentReaderPort::class, DatabaseCustomerPaymentReaderAdapter::class);
        $this->app->singleton(CustomerRefundWriterPort::class, DatabaseCustomerRefundWriterAdapter::class);
        $this->app->singleton(CustomerRefundReaderPort::class, DatabaseCustomerRefundReaderAdapter::class);
        $this->app->singleton(RefundComponentAllocationWriterPort::class, DatabaseRefundComponentAllocationWriterAdapter::class);
        $this->app->singleton(RefundComponentAllocationReaderPort::class, DatabaseRefundComponentAllocationReaderAdapter::class);
        $this->app->singleton(PaymentAllocationWriterPort::class, DatabasePaymentAllocationWriterAdapter::class);
        $this->app->singleton(PaymentAllocationReaderPort::class, DatabasePaymentAllocationReaderAdapter::class);
        $this->app->singleton(PaymentComponentAllocationWriterPort::class, DatabasePaymentComponentAllocationWriterAdapter::class);
        $this->app->singleton(PaymentComponentAllocationReaderPort::class, DatabasePaymentComponentAllocationReaderAdapter::class);

    }
}
