<?php

// @audit-skip: line-limit

declare(strict_types=1);

namespace App\Providers;

use App\Application\ProductCatalog\Context\ProductChangeContext;
use App\Adapters\Out\Audit\DatabaseAuditLogAdapter;
use App\Adapters\Out\Audit\DatabaseAuditLogReaderAdapter;
use App\Adapters\Out\Auth\LaravelUuidAdapter;
use App\Adapters\Out\Clock\SystemClockAdapter;
use App\Adapters\Out\Expense\DatabaseExpenseCategoryReaderAdapter;
use App\Adapters\Out\Expense\DatabaseExpenseCategoryWriterAdapter;
use App\Adapters\Out\Expense\DatabaseExpenseCategoryTableReaderAdapter;
use App\Adapters\Out\Expense\DatabaseOperationalExpenseWriterAdapter;
use App\Adapters\Out\Expense\DatabaseOperationalExpenseTableReaderAdapter;
use App\Adapters\Out\EmployeeFinance\DatabaseEmployeePayrollTableReaderAdapter;
use App\Adapters\Out\IdentityAccess\DatabaseActorAccessReaderAdapter;
use App\Adapters\Out\IdentityAccess\DatabaseAdminCashierAreaAccessStateAdapter;
use App\Adapters\Out\IdentityAccess\DatabaseAdminTransactionCapabilityStateAdapter;
use App\Adapters\Out\Inventory\DatabaseInventoryMovementReaderAdapter;
use App\Adapters\Out\Inventory\DatabaseInventoryMovementWriterAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryCostingProjectionWriterAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryCostingReaderAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryCostingWriterAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryProjectionWriterAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryReaderAdapter;
use App\Adapters\Out\Inventory\DatabaseProductInventoryWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteCorrectionHistoryReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteMutationEventWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteMutationSnapshotWriterAdapter;
use App\Adapters\Out\Note\DatabaseNoteReaderAdapter;
use App\Adapters\Out\Note\DatabaseNoteWriterAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftDeleterAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftReaderAdapter;
use App\Adapters\Out\Note\DatabaseTransactionWorkspaceDraftWriterAdapter;
use App\Adapters\Out\Note\DatabaseWorkItemWriterAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerPaymentReaderAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerPaymentWriterAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerRefundReaderAdapter;
use App\Adapters\Out\Payment\DatabaseCustomerRefundWriterAdapter;
use App\Adapters\Out\Payment\DatabaseRefundComponentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabaseRefundComponentAllocationWriterAdapter;
use App\Adapters\Out\Payment\DatabasePaymentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabasePaymentAllocationWriterAdapter;
use App\Adapters\Out\Payment\DatabasePaymentComponentAllocationReaderAdapter;
use App\Adapters\Out\Payment\DatabasePaymentComponentAllocationWriterAdapter;
use App\Adapters\Out\Persistence\DatabaseTransactionManagerAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceLineReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierInvoiceWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseProcurementInvoiceDetailReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentProofAttachmentReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentProofAttachmentWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierPaymentWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReceiptLineReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierReceiptWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierWriterAdapter;
use App\Adapters\Out\Procurement\DatabaseProcurementInvoiceTableReaderAdapter;
use App\Adapters\Out\Procurement\DatabaseSupplierTableReaderAdapter;
use App\Adapters\Out\ProductCatalog\DatabaseProductDuplicateCheckerAdapter;
use App\Adapters\Out\ProductCatalog\DatabaseProductReaderAdapter;
use App\Adapters\Out\ProductCatalog\DatabaseProductTableReaderAdapter;
use App\Adapters\Out\ProductCatalog\DatabaseProductWriterAdapter;
use App\Adapters\Out\ProductCatalog\DatabaseVersionedProductWriterAdapter;
use App\Adapters\Out\Reporting\DatabaseEmployeeDebtReportingSourceReaderAdapter;
use App\Adapters\Out\Reporting\DatabaseInventoryMovementReportingSourceReaderAdapter;
use App\Adapters\Out\Reporting\DatabaseOperationalExpenseReportingSourceReaderAdapter;
use App\Adapters\Out\Reporting\DatabaseOperationalProfitReportingSourceReaderAdapter;
use App\Adapters\Out\Reporting\DatabaseSupplierPayableReportingSourceReaderAdapter;
use App\Adapters\Out\Reporting\DatabaseTransactionReportingSourceReaderAdapter;
use App\Application\Inventory\Policies\DefaultNegativeStockPolicy;
use App\Application\Inventory\Services\InventoryCostingProjectionBuilder;
use App\Application\Inventory\Services\InventoryProjectionBuilder;
use App\Application\Inventory\Services\InventoryProjectionService;
use App\Application\Inventory\Services\IssueInventoryOperation;
use App\Application\Note\Policies\NoteAddabilityPolicy;
use App\Application\Note\Policies\CashierNoteAccessGuard;
use App\Application\Note\Policies\NotePaidStatusPolicy;
use App\Application\Note\Services\AddWorkItemErrorClassifier;
use App\Application\Note\Services\AutoCloseNoteWhenFullyPaid;
use App\Application\Note\Services\NoteCorrectionSnapshotBuilder;
use App\Application\Note\Services\NoteRowSettlementSummaryBuilder;
use App\Application\Note\Services\PersistNoteMutationTimeline;
use App\Application\Note\Services\FinalizePaidNoteCorrection;
use App\Application\Note\Services\WorkItemFactory;
use App\Application\Note\Services\WorkItemStatusTransitionService;
use App\Application\Payment\Services\AllocatePaymentAcrossComponents;
use App\Application\Payment\Services\AllocatePaymentErrorClassifier;
use App\Application\Payment\Services\AllocateRefundAcrossComponents;
use App\Application\Payment\Services\ResolveNotePayableComponents;
use App\Application\Procurement\Services\SupplierInvoiceFactory;
use App\Application\Procurement\Services\SupplierReceiptFactory;
use App\Application\Procurement\Services\SupplierService;
use App\Application\System\Health\HealthCheckHandler;
use App\Core\Inventory\Policies\NegativeStockPolicy;
use App\Core\ProductCatalog\Policies\MinSellingPricePolicy;
use App\Ports\In\HealthCheckUseCase;
use App\Ports\Out\AuditLogPort;
use App\Ports\Out\AuditLogReaderPort;
use App\Ports\Out\ClockPort;
use App\Ports\Out\EmployeeFinance\EmployeeDebtAdjustmentWriterPort;
use App\Ports\Out\EmployeeFinance\EmployeeDebtReaderPort;
use App\Ports\Out\EmployeeFinance\EmployeeDebtWriterPort;
use App\Ports\Out\EmployeeFinance\EmployeeReaderPort;
use App\Ports\Out\EmployeeFinance\EmployeeWriterPort;
use App\Ports\Out\EmployeeFinance\PayrollDisbursementWriterPort;
use App\Ports\Out\EmployeeFinance\PayrollDisbursementReversalWriterPort;
use App\Ports\Out\EmployeeFinance\EmployeePayrollTableReaderPort;
use App\Ports\Out\Expense\ExpenseCategoryReaderPort;
use App\Ports\Out\Expense\ExpenseCategoryWriterPort;
use App\Ports\Out\Expense\ExpenseCategoryTableReaderPort;
use App\Ports\Out\Expense\OperationalExpenseWriterPort;
use App\Ports\Out\Expense\OperationalExpenseTableReaderPort;
use App\Ports\Out\IdentityAccess\ActorAccessReaderPort;
use App\Ports\Out\IdentityAccess\AdminCashierAreaAccessStatePort;
use App\Ports\Out\IdentityAccess\AdminTransactionCapabilityStatePort;
use App\Ports\Out\Inventory\InventoryMovementReaderPort;
use App\Ports\Out\Inventory\InventoryMovementWriterPort;
use App\Ports\Out\Inventory\ProductInventoryCostingProjectionWriterPort;
use App\Ports\Out\Inventory\ProductInventoryCostingReaderPort;
use App\Ports\Out\Inventory\ProductInventoryCostingWriterPort;
use App\Ports\Out\Inventory\ProductInventoryProjectionWriterPort;
use App\Ports\Out\Inventory\ProductInventoryReaderPort;
use App\Ports\Out\Inventory\ProductInventoryWriterPort;
use App\Ports\Out\Note\NoteCorrectionHistoryReaderPort;
use App\Ports\Out\Note\NoteMutationEventWriterPort;
use App\Ports\Out\Note\NoteMutationSnapshotWriterPort;
use App\Ports\Out\Note\NoteReaderPort;
use App\Ports\Out\Note\NoteWriterPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftDeleterPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftReaderPort;
use App\Ports\Out\Note\TransactionWorkspaceDraftWriterPort;
use App\Ports\Out\Note\WorkItemWriterPort;
use App\Ports\Out\Payment\CustomerPaymentReaderPort;
use App\Ports\Out\Payment\CustomerPaymentWriterPort;
use App\Ports\Out\Payment\CustomerRefundReaderPort;
use App\Ports\Out\Payment\CustomerRefundWriterPort;
use App\Ports\Out\Payment\PaymentAllocationReaderPort;
use App\Ports\Out\Payment\PaymentAllocationWriterPort;
use App\Ports\Out\Payment\PaymentComponentAllocationReaderPort;
use App\Ports\Out\Payment\PaymentComponentAllocationWriterPort;
use App\Ports\Out\Payment\RefundComponentAllocationReaderPort;
use App\Ports\Out\Payment\RefundComponentAllocationWriterPort;
use App\Ports\Out\Procurement\SupplierInvoiceLineReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceReaderPort;
use App\Ports\Out\Procurement\SupplierInvoiceWriterPort;
use App\Ports\Out\Procurement\ProcurementInvoiceDetailReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentProofAttachmentReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentProofAttachmentWriterPort;
use App\Ports\Out\Procurement\SupplierPaymentReaderPort;
use App\Ports\Out\Procurement\SupplierPaymentWriterPort;
use App\Ports\Out\Procurement\SupplierReaderPort;
use App\Ports\Out\Procurement\SupplierReceiptLineReaderPort;
use App\Ports\Out\Procurement\SupplierReceiptWriterPort;
use App\Ports\Out\Procurement\SupplierWriterPort;
use App\Ports\Out\Procurement\ProcurementInvoiceTableReaderPort;
use App\Ports\Out\Procurement\SupplierTableReaderPort;
use App\Ports\Out\ProductCatalog\ProductDuplicateCheckerPort;
use App\Ports\Out\ProductCatalog\ProductReaderPort;
use App\Ports\Out\ProductCatalog\ProductTableReaderPort;
use App\Ports\Out\ProductCatalog\ProductWriterPort;
use App\Ports\Out\Reporting\EmployeeDebtReportingSourceReaderPort;
use App\Ports\Out\Reporting\InventoryMovementReportingSourceReaderPort;
use App\Ports\Out\Reporting\OperationalExpenseReportingSourceReaderPort;
use App\Ports\Out\Reporting\OperationalProfitReportingSourceReaderPort;
use App\Ports\Out\Reporting\SupplierPayableReportingSourceReaderPort;
use App\Ports\Out\Reporting\TransactionReportingSourceReaderPort;
use App\Ports\Out\TransactionManagerPort;
use App\Ports\Out\UuidPort;
use Illuminate\Support\ServiceProvider;

class HexagonalServiceProvider extends ServiceProvider
{
    public function register(): void
    {
        $this->app->scoped(ProductChangeContext::class, fn (): ProductChangeContext => new ProductChangeContext());
        $this->app->bind(HealthCheckUseCase::class, HealthCheckHandler::class);

        $this->app->singleton(ClockPort::class, SystemClockAdapter::class);
        $this->app->singleton(UuidPort::class, LaravelUuidAdapter::class);
        $this->app->singleton(AuditLogPort::class, DatabaseAuditLogAdapter::class);
        $this->app->singleton(AuditLogReaderPort::class, DatabaseAuditLogReaderAdapter::class);
        $this->app->singleton(TransactionManagerPort::class, DatabaseTransactionManagerAdapter::class);

        $this->app->singleton(NegativeStockPolicy::class, DefaultNegativeStockPolicy::class);
        $this->app->singleton(MinSellingPricePolicy::class);
        $this->app->singleton(NotePaidStatusPolicy::class);
        $this->app->singleton(NoteAddabilityPolicy::class);
        $this->app->singleton(CashierNoteAccessGuard::class);

        $this->app->singleton(InventoryProjectionService::class);
        $this->app->singleton(IssueInventoryOperation::class);
        $this->app->singleton(InventoryCostingProjectionBuilder::class);
        $this->app->singleton(InventoryProjectionBuilder::class);
        $this->app->singleton(WorkItemFactory::class);
        $this->app->singleton(WorkItemStatusTransitionService::class);
        $this->app->singleton(AddWorkItemErrorClassifier::class);
        $this->app->singleton(AutoCloseNoteWhenFullyPaid::class);
        $this->app->singleton(NoteCorrectionSnapshotBuilder::class);
        $this->app->singleton(NoteRowSettlementSummaryBuilder::class);
        $this->app->singleton(PersistNoteMutationTimeline::class);
        $this->app->singleton(FinalizePaidNoteCorrection::class);
        $this->app->singleton(AllocatePaymentErrorClassifier::class);
        $this->app->singleton(ResolveNotePayableComponents::class);
        $this->app->singleton(AllocatePaymentAcrossComponents::class);
        $this->app->singleton(AllocateRefundAcrossComponents::class);
        $this->app->singleton(SupplierService::class);
        $this->app->singleton(SupplierInvoiceFactory::class);
        $this->app->singleton(SupplierReceiptFactory::class);

        $this->app->singleton(ActorAccessReaderPort::class, DatabaseActorAccessReaderAdapter::class);
        $this->app->singleton(AdminTransactionCapabilityStatePort::class, DatabaseAdminTransactionCapabilityStateAdapter::class);
        $this->app->singleton(AdminCashierAreaAccessStatePort::class, DatabaseAdminCashierAreaAccessStateAdapter::class);

        $this->app->singleton(ProductReaderPort::class, DatabaseProductReaderAdapter::class);
        $this->app->singleton(ProductTableReaderPort::class, DatabaseProductTableReaderAdapter::class);
        $this->app->scoped(ProductWriterPort::class, DatabaseVersionedProductWriterAdapter::class);
        $this->app->singleton(ProductDuplicateCheckerPort::class, DatabaseProductDuplicateCheckerAdapter::class);

        $this->app->singleton(SupplierReaderPort::class, DatabaseSupplierReaderAdapter::class);
        $this->app->singleton(SupplierWriterPort::class, DatabaseSupplierWriterAdapter::class);
        $this->app->singleton(ProcurementInvoiceTableReaderPort::class, DatabaseProcurementInvoiceTableReaderAdapter::class);
        $this->app->singleton(SupplierTableReaderPort::class, DatabaseSupplierTableReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceWriterPort::class, DatabaseSupplierInvoiceWriterAdapter::class);
        $this->app->singleton(SupplierInvoiceReaderPort::class, DatabaseSupplierInvoiceReaderAdapter::class);
        $this->app->singleton(ProcurementInvoiceDetailReaderPort::class, DatabaseProcurementInvoiceDetailReaderAdapter::class);
        $this->app->singleton(SupplierInvoiceLineReaderPort::class, DatabaseSupplierInvoiceLineReaderAdapter::class);
        $this->app->singleton(SupplierReceiptLineReaderPort::class, DatabaseSupplierReceiptLineReaderAdapter::class);
        $this->app->singleton(SupplierReceiptWriterPort::class, DatabaseSupplierReceiptWriterAdapter::class);
        $this->app->singleton(SupplierPaymentWriterPort::class, DatabaseSupplierPaymentWriterAdapter::class);
        $this->app->singleton(SupplierPaymentReaderPort::class, DatabaseSupplierPaymentReaderAdapter::class);
        $this->app->singleton(SupplierPaymentProofAttachmentWriterPort::class, DatabaseSupplierPaymentProofAttachmentWriterAdapter::class);
        $this->app->singleton(SupplierPaymentProofAttachmentReaderPort::class, DatabaseSupplierPaymentProofAttachmentReaderAdapter::class);

        $this->app->singleton(InventoryMovementReaderPort::class, DatabaseInventoryMovementReaderAdapter::class);
        $this->app->singleton(InventoryMovementWriterPort::class, DatabaseInventoryMovementWriterAdapter::class);
        $this->app->singleton(ProductInventoryReaderPort::class, DatabaseProductInventoryReaderAdapter::class);
        $this->app->singleton(ProductInventoryWriterPort::class, DatabaseProductInventoryWriterAdapter::class);
        $this->app->singleton(ProductInventoryProjectionWriterPort::class, DatabaseProductInventoryProjectionWriterAdapter::class);
        $this->app->singleton(ProductInventoryCostingReaderPort::class, DatabaseProductInventoryCostingReaderAdapter::class);
        $this->app->singleton(ProductInventoryCostingWriterPort::class, DatabaseProductInventoryCostingWriterAdapter::class);
        $this->app->singleton(ProductInventoryCostingProjectionWriterPort::class, DatabaseProductInventoryCostingProjectionWriterAdapter::class);

        $this->app->singleton(NoteReaderPort::class, DatabaseNoteReaderAdapter::class);
        $this->app->singleton(NoteWriterPort::class, DatabaseNoteWriterAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftWriterPort::class, DatabaseTransactionWorkspaceDraftWriterAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftReaderPort::class, DatabaseTransactionWorkspaceDraftReaderAdapter::class);
        $this->app->singleton(TransactionWorkspaceDraftDeleterPort::class, DatabaseTransactionWorkspaceDraftDeleterAdapter::class);
        $this->app->singleton(WorkItemWriterPort::class, DatabaseWorkItemWriterAdapter::class);
        $this->app->singleton(NoteMutationEventWriterPort::class, DatabaseNoteMutationEventWriterAdapter::class);
        $this->app->singleton(NoteMutationSnapshotWriterPort::class, DatabaseNoteMutationSnapshotWriterAdapter::class);
        $this->app->singleton(NoteCorrectionHistoryReaderPort::class, DatabaseNoteCorrectionHistoryReaderAdapter::class);

        $this->app->singleton(CustomerPaymentWriterPort::class, DatabaseCustomerPaymentWriterAdapter::class);
        $this->app->singleton(CustomerPaymentReaderPort::class, DatabaseCustomerPaymentReaderAdapter::class);
        $this->app->singleton(CustomerRefundWriterPort::class, DatabaseCustomerRefundWriterAdapter::class);
        $this->app->singleton(CustomerRefundReaderPort::class, DatabaseCustomerRefundReaderAdapter::class);
        $this->app->singleton(RefundComponentAllocationWriterPort::class, DatabaseRefundComponentAllocationWriterAdapter::class);
        $this->app->singleton(RefundComponentAllocationReaderPort::class, DatabaseRefundComponentAllocationReaderAdapter::class);
        $this->app->singleton(PaymentAllocationWriterPort::class, DatabasePaymentAllocationWriterAdapter::class);
        $this->app->singleton(PaymentAllocationReaderPort::class, DatabasePaymentAllocationReaderAdapter::class);
        $this->app->singleton(PaymentComponentAllocationWriterPort::class, DatabasePaymentComponentAllocationWriterAdapter::class);
        $this->app->singleton(PaymentComponentAllocationReaderPort::class, DatabasePaymentComponentAllocationReaderAdapter::class);

        $this->app->singleton(TransactionReportingSourceReaderPort::class, DatabaseTransactionReportingSourceReaderAdapter::class);
        $this->app->singleton(OperationalExpenseReportingSourceReaderPort::class, DatabaseOperationalExpenseReportingSourceReaderAdapter::class);
        $this->app->singleton(EmployeeDebtReportingSourceReaderPort::class, DatabaseEmployeeDebtReportingSourceReaderAdapter::class);
        $this->app->singleton(SupplierPayableReportingSourceReaderPort::class, DatabaseSupplierPayableReportingSourceReaderAdapter::class);
        $this->app->singleton(InventoryMovementReportingSourceReaderPort::class, DatabaseInventoryMovementReportingSourceReaderAdapter::class);
        $this->app->singleton(OperationalProfitReportingSourceReaderPort::class, DatabaseOperationalProfitReportingSourceReaderAdapter::class);

        $this->app->singleton(EmployeeReaderPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeReaderAdapter::class);
        $this->app->singleton(EmployeeWriterPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeWriterAdapter::class);
        $this->app->singleton(\App\Ports\Out\EmployeeFinance\EmployeeTableReaderPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeTableReaderAdapter::class);
        $this->app->singleton(EmployeeDebtReaderPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeDebtReaderAdapter::class);
        $this->app->singleton(EmployeeDebtAdjustmentWriterPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeDebtAdjustmentWriterAdapter::class);
        $this->app->singleton(EmployeeDebtWriterPort::class, \App\Adapters\Out\EmployeeFinance\DatabaseEmployeeDebtWriterAdapter::class);
        $this->app->singleton(EmployeePayrollTableReaderPort::class, DatabaseEmployeePayrollTableReaderAdapter::class); 
        $this->app->singleton(PayrollDisbursementWriterPort::class, \App\Adapters\Out\EmployeeFinance\DatabasePayrollDisbursementWriterAdapter::class);
        $this->app->singleton(PayrollDisbursementReversalWriterPort::class, \App\Adapters\Out\EmployeeFinance\DatabasePayrollDisbursementReversalWriterAdapter::class);
        $this->app->singleton(\App\Ports\Out\EmployeeFinance\PayrollTableReaderPort::class, \App\Adapters\Out\EmployeeFinance\DatabasePayrollTableReaderAdapter::class);

        $this->app->singleton(ExpenseCategoryReaderPort::class, DatabaseExpenseCategoryReaderAdapter::class);
        $this->app->singleton(ExpenseCategoryWriterPort::class, DatabaseExpenseCategoryWriterAdapter::class);
        $this->app->singleton(ExpenseCategoryTableReaderPort::class, DatabaseExpenseCategoryTableReaderAdapter::class);
        $this->app->singleton(OperationalExpenseWriterPort::class, DatabaseOperationalExpenseWriterAdapter::class);
        $this->app->singleton(OperationalExpenseTableReaderPort::class, DatabaseOperationalExpenseTableReaderAdapter::class);
    }
}
