#!/usr/bin/env bash
set -eu

echo '== AI_RULES structure =='
find AI_RULES -maxdepth 3 -type f | sort

echo
echo '== required files check =='
required_files='
AI_RULES/00_INDEX.md
AI_RULES/01_DECISION_POLICY.md
AI_RULES/02_GPT_BOOTSTRAP_PROMPT.md
AI_RULES/03_SESSION_START_PROTOCOL.md
AI_RULES/04_HANDOFF_TEMPLATE.md
AI_RULES/05_FINAL_REVIEW_CHECKLIST.md
AI_RULES/10_CORE/10_SCOPE_AND_FACTS.md
AI_RULES/10_CORE/11_BLUEPRINT_FIRST.md
AI_RULES/10_CORE/12_STEP_BY_STEP_EXECUTION.md
AI_RULES/10_CORE/13_PROOF_AND_PROGRESS.md
AI_RULES/20_WORKFLOW/20_RESPONSE_STRUCTURE.md
AI_RULES/20_WORKFLOW/21_ACTIVE_STEP_POLICY.md
AI_RULES/20_WORKFLOW/22_OPTION_EVALUATION.md
AI_RULES/20_WORKFLOW/23_HANDOFF_POLICY.md
AI_RULES/30_OUTPUT/30_FILE_DELIVERY.md
AI_RULES/30_OUTPUT/31_MARKDOWN_OUTPUT_RULE.md
AI_RULES/30_OUTPUT/32_BLADE_RULE.md
AI_RULES/30_OUTPUT/33_TERMINAL_COMMAND_DELIVERY.md
AI_RULES/40_ARCHITECTURE/40_HEXAGONAL_BASELINE.md
AI_RULES/40_ARCHITECTURE/41_PUBLIC_CONTRACTS.md
AI_RULES/40_ARCHITECTURE/42_ERROR_HANDLING_AND_REDACTION.md
AI_RULES/40_ARCHITECTURE/43_DEBUG_GATING.md
AI_RULES/40_ARCHITECTURE/44_AUDIT_AND_DOD.md
AI_RULES/50_DOMAIN_KASIR/50_FINAL_DOMAIN_MAP.md
AI_RULES/50_DOMAIN_KASIR/51_UI_TERMS_AND_STATUS.md
AI_RULES/50_DOMAIN_KASIR/52_PAYMENT_LIFECYCLE.md
AI_RULES/50_DOMAIN_KASIR/53_REPORTING_BOUNDARY.md
AI_RULES/60_STACK/60_LARAVEL_RULES.md
AI_RULES/60_STACK/61_GO_RULES.md
AI_RULES/60_STACK/62_AWS_BASELINE.md
AI_RULES/99_CHANGELOG.md
'
printf '%s\n' "$required_files" | sed '/^$/d' | while IFS= read -r f; do
  if [ -f "$f" ]; then
    echo "[OK] $f"
  else
    echo "[MISSING] $f"
    exit 1
  fi
done

echo
echo '== keyword checks =='
grep -n 'Mandatory Read Order' AI_RULES/00_INDEX.md
grep -n 'Rule Hierarchy' AI_RULES/01_DECISION_POLICY.md
grep -n 'Implementation Gate' AI_RULES/10_CORE/11_BLUEPRINT_FIRST.md
grep -n 'Hanya satu step aktif' AI_RULES/02_GPT_BOOTSTRAP_PROMPT.md
grep -n 'Target akhir lifecycle pembayaran adalah partial payment eksplisit' AI_RULES/50_DOMAIN_KASIR/52_PAYMENT_LIFECYCLE.md
grep -n 'outer fence wajib menggunakan `text`' AI_RULES/30_OUTPUT/31_MARKDOWN_OUTPUT_RULE.md
grep -n '## Next step' AI_RULES/04_HANDOFF_TEMPLATE.md

echo
echo '== audit complete =='
